apiVersion: v1
kind: ConfigMap
metadata:
  name: capsule-tenant-terra-manifests
  namespace: projectsveltos
data:
  tenant.yaml: |
    apiVersion: capsule.clastix.io/v1beta2
    kind: Tenant
    metadata:
      name: terra
    spec:
      owners:
        - name: terra
          kind: Group
