apiVersion: v1
kind: ConfigMap
metadata:
  name: capsule-tenant-orion-manifests
  namespace: projectsveltos
data:
  tenant-orion.yaml: |
    apiVersion: capsule.clastix.io/v1beta2
    kind: Tenant
    metadata:
      name: orion
    spec:
      owners:
        - name: alice
          kind: User
