apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: capsule-tenant-terra
spec:
  clusterSelector:
    matchLabels:
      env: tenant-b
  syncMode: Continuous
  policyRefs:
    - kind: ConfigMap
      namespace: projectsveltos
      name: capsule-tenant-terra-manifests
