apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: nginx-multi-tenant
spec:
  clusterSelector:
    matchLabels:
      env: tenant-b
  syncMode: Continuous
  policyRefs:
    - kind: ConfigMap
      namespace: projectsveltos
      name: nginx-multi-tenant-manifests
