apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: nginx-orion-atlas
spec:
  clusterSelector:
    matchLabels:
      env: tenant-b
  syncMode: Continuous
  policyRefs:
    - kind: ConfigMap
      name: nginx-orion-atlas-manifests
      namespace: projectsveltos
